using System;
using UnityEditor;
using UnityEngine;

// ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ public private protected
public class PlayerController : MonoBehaviour
{
    // Start, Update ï¿½ï¿½ï¿½ï¿½Æ¼ ï¿½Ìºï¿½Æ® ï¿½Ô¼ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½Ì¸ï¿½ï¿½ï¿½ ï¿½Ö´ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
    // ï¿½ï¿½ï¿½ï¿½ ï¿½Ì¸ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½? ï¿½ï¿½ï¿½ï¿½Æ¼ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½Ø³ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½Ã°ï¿½ï¿½ï¿½ ï¿½ï¿½ ï¿½Ô¼ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½

    // Start is called before the first frame update
    // Ã¹ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½Ò·ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ (ï¿½Ñ¹ï¿½) ï¿½ï¿½ï¿½ï¿½ï¿½Ñ´ï¿½. ï¿½Ñ¹ï¿½ï¿½ï¿½!

    // ï¿½Óµï¿½, ï¿½ï¿½ï¿½ï¿½
    [Header("ï¿½Ìµï¿½")]
    public float moveSpeed = 5f;   // Ä³ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½Ìµï¿½ ï¿½Óµï¿½
    public float JumpForce = 10f;
    private float moveInput;  // ï¿½Ã·ï¿½ï¿½Ì¾ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ ï¿½ï¿½Ç² ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½

    //public Transform startTransform; // Ä³ï¿½ï¿½ï¿½Í°ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½Ä¡
    public Rigidbody2D rigidbody2D;  // ï¿½ï¿½ï¿½ï¿½(ï¿½ï¿½Ã¼) ï¿½ï¿½ï¿½ï¿½ï¿?ï¿½ï¿½ï¿½ï¿½ï¿½Ï´ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Æ®

    [Header("ï¿½ï¿½ï¿½ï¿½")]
    public bool isGrounded;          // true : Ä³ï¿½ï¿½ï¿½Í°ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ ï¿½ï¿½ ï¿½Ö´ï¿½ ï¿½ï¿½ï¿½ï¿½, false : ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
    public float groundDistance = 2f;
    public LayerMask groundLayer;

    [Header("Flip")]
    public SpriteRenderer spriteRenderer;
    private bool facingRight = true;
    private int facingDirection = 1;

    [Header("HP")]
    public int currentHP;
    public int maxHP = 5;

  

    [SerializeField] ParticleController particleController;
    public Animator animator;
    private bool isMove;

    private void Awake()
    {
        currentHP = maxHP;
    }

    void Start()
    {
        rigidbody2D = GetComponent<Rigidbody2D>();
            
        Debug.Log("Hello Unity");
        // ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ ï¿½ï¿½Ä¡ <= ï¿½ï¿½ï¿½Î¿ï¿½ x,y ï¿½ï¿½ï¿½ï¿½ï¿½Ï´ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ Å¸ï¿½ï¿½( ï¿½ï¿½ï¿½ï¿½ xï¿½ï¿½Ç¥, 10 yï¿½ï¿½Ç¥)
        //transform.position = new Vector2(transform.position.x, 10);

        // ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ ï¿½ï¿½Ä¡ï¿½ï¿½ startTransformï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
        InitializePlayerStatus();
    }

    void InitializePlayerStatus()
    {
        //transform.position = startTransform.position;
        rigidbody2D.velocity = Vector2.zero;
        facingRight = true;
        spriteRenderer.flipX = false;
    }

    // Update is called once per frame
    // 1 ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ È£ï¿½ï¿½È´ï¿? - ï¿½İºï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ 
    void Update()
    {
        // ï¿½Ô¼ï¿½ ï¿½Ì¸ï¿½ ï¿½Õ¿ï¿½ ï¿½ï¿½ï¿½ì½ºÄ¿ï¿½ï¿½ï¿½ï¿½ ï¿½Î°ï¿½ Ctlr + R + R 
        HandleAnimation();
        CollisionCheck();
        HandleInput();
        HandleFlip();
        Move();
        FallDownCheck();
    }

    private void FallDownCheck()
    {
        // yï¿½ï¿½ ï¿½ï¿½ï¿½Ì°ï¿½ Æ¯ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½Ñ´ï¿½. => ï¿½æµ¹ Ã¼Å© ï¿½ï¿½Ã¼
        if(transform.position.y < -11)
        {
            InitializePlayerStatus();
        }
    }

    private void HandleAnimation()
    {
        // rigidbody.velocity : ï¿½ï¿½ï¿½ï¿½ rigidbody ï¿½Óµï¿½ = 0 ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½Ê´ï¿½ ï¿½ï¿½ï¿½ï¿½, !=0 ï¿½ï¿½ï¿½ï¿½ï¿½Ì°ï¿½ ï¿½Ö´ï¿½ ï¿½ï¿½ï¿½ï¿½
        isMove = rigidbody2D.velocity.x != 0;  
        animator.SetBool("isMove", isMove);
        animator.SetBool("isGrounded", isGrounded);
        // SetFloat ï¿½Ô¼ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½Ø¼ï¿½ yï¿½Ö´ï¿½ï¿½ï¿½ ï¿½ï¿½ 1ï¿½ï¿½ ï¿½ï¿½È¯.. y ï¿½Ö¼ï¿½ï¿½ï¿½ ï¿½ï¿½ -1ï¿½ï¿½ ï¿½ï¿½È¯
        // ï¿½ï¿½ï¿½ï¿½ Å°ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½. ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ y ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½, ï¿½ß·Â¿ï¿½ ï¿½ï¿½ï¿½Ø¼ï¿½ ï¿½ï¿½ï¿½ï¿½ y ï¿½Óµï¿½ -ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ì´Ï´ï¿½.
        animator.SetFloat("yVelocity", rigidbody2D.velocity.y);  
    }

    /// <summary>
    /// ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½Æ´ï¿½ï¿½ï¿½ Ã¼Å© ï¿½Ï´ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿?-> Collider Check
    /// </summary>
    private void CollisionCheck()
    {
        isGrounded = Physics2D.Raycast(transform.position, Vector2.down, groundDistance, groundLayer);

        particleController.isGround = isGrounded;
    }
    /// <summary>
    /// ï¿½Ã·ï¿½ï¿½Ì¾ï¿½ï¿½ï¿½ ï¿½Ô·ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½Ş¾Æ¿Í¾ï¿½ ï¿½Õ´Ï´ï¿½.  a,d Å°ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ ï¿½ï¿½ Å°ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ -1 ~ 1 ï¿½ï¿½È¯ï¿½Ï´ï¿½ Å¬ï¿½ï¿½ï¿½ï¿½
    /// </summary>
    private void HandleInput()
    {
        if (Input.GetKeyDown(KeyCode.F))
        {
            particleController.PlayParticle();
        }

        moveInput = Input.GetAxis("Horizontal");

        JumpButton();
    }

    private void HandleFlip()
    {
        // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½Ù¶óº¸°ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ 
        if(facingRight && moveInput < 0)
        {
            Flip();
        }
        // ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½Ù¶óº¸°ï¿½ ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½
        else if(!facingRight && moveInput > 0)
        {
            Flip();
        }
    }

    private void Flip()
    {
        facingDirection = facingDirection * -1;
        facingRight = !facingRight;
        spriteRenderer.flipX = !facingRight;
    }

    private void JumpButton()
    {
        if (Input.GetKeyDown(KeyCode.Space) && isGrounded == true)
        {
            Jump();
        }
    }

    private void Jump()
    {
        rigidbody2D.velocity = new Vector2(rigidbody2D.velocity.x, JumpForce);
        // ?í”„ ?¬ìš´??ì¶œë ¥.
        // SFX ë°°ì—´???±ë¡???¨ê³¼??ì¶œë ¥ ?«ì 2??Jump1???´ë‹¹??
        if (AudioManager.instance == null)
        {
            Debug.LogWarning($"{nameof(AudioManager)}??instanceê°€ ?†ìŠµ?ˆë‹¤");
            return;
        }
        AudioManager.instance.PlaySFX(2);
    }


    private void Move()
    {
        rigidbody2D.velocity = new Vector2(moveSpeed * moveInput, rigidbody2D.velocity.y);
    }


    private void PlatformMove(Vector2 power)
    {
        rigidbody2D.velocity = power;
    }

    private void OnDrawGizmos()
    {
        Gizmos.color = Color.red;
        Gizmos.DrawLine(transform.position, new Vector2(transform.position.x, transform.position.y - groundDistance));
    }

}
